### ISSUE TITLE
Mohammad, really thanks from Korea.

### ISSUE THREAD

**Issue by junoru** [MohammadFneish7/Keras_LSTM_Diagram#1]
finally I got to your fancy explaination, midnight south Korea. really thank your for your dedication for sily like me. haha Thanks again!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

PS. if you don't mind, Can I translate it into Korean?

**Comment by MohammadFneish7** [comment]
@junoru hhhhh that is my pleasure, happy to help. Create a fork and do whatever you want my friend it is licensed under GPL.
